sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t artyomsidun/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true artyomsidun/react-test npm test

after_success:
  - docker build -t artyomsidun/multi-client ./client
  - docker build -t artyomsidun/multi-nginx ./nginx
  - docker build -t artyomsidun/multi-server ./server
  - docker build -t artyomsidun/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push artyomsidun/multi-client
  - docker push artyomsidun/multi-nginx
  - docker push artyomsidun/multi-server
  - docker push artyomsidun/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-844847910395"
  bucket_path: "docker-multi"
  on:
    branch:  main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY